# Site settings
title: arkountos | Portfolio
description: A portfolio site to showcase my favorite projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hey, I'm Fivos
user_description: "I'm Fivos Iliadis and I'm a PhD Student @ National Technical University of Athens. I got my MEng at the ECE department of NTUA, and I am now working on Computer Architecture and Systems Security. "
user_title: a PhD Student at ECE-NTUA, and I like computers and stuff.
email: fivosiliadis@gmail.com
twitter_username: arkountos1
github_username:  arkountos

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
